platform: linux

image_resource:
    type: docker-image
    source: { repository: maven, tag: 3.3.9-jdk-8 }

inputs:
- name: hello-world

run:
  chmod +x hello-world/build.sh
  path: hello-world/build.sh
